criação da aba de ferramentas
Requisitos-de-Software/2024.2-TesouroDireto pull request #20
Opened 2024-10-29 16:36 UTC by juliatakaki

2024-10-29 18:37 UTC, thaleseuflauzino requested changes

2024-10-29 18:37 UTC, thaleseuflauzino commented on docs/Planejamento-do-projeto/cronograma.md
> +      <td>Thales Henrique</td>
<td>Thales Euflauzino</td>

2024-10-29 18:38 UTC, ViictorHugoo requested changes
Faltam ferramentas: this person doenst exist, youtube, google sheets, notion,

2024-10-30 23:43 UTC, ViictorHugoo approved these changes

2024-10-30 23:43 UTC, merged